### ISSUE TITLE
Server-Side Crash - ISound Exception

### ISSUE THREAD

**Issue by JayJTD** [Hugman76/Mubble#59]
When loading Mubble 3.0 into a Minecraft Server configuration, the server will crash and the console will produce errors relating to an ISound exception.
Logs are:
``` 
>....       [09:23:16 [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: net/minecraft/client/audio/ISound]
    Index: 8
    Listeners:
        0: NORMAL
        1: ASM: class hugman.mubble.Mubble$ModRegistryEvents entitiesRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        2: ASM: class hugman.mubble.Mubble$ModRegistryEvents soundsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        3: ASM: class hugman.mubble.Mubble$ModRegistryEvents potionsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        4: ASM: class hugman.mubble.Mubble$ModRegistryEvents biomesRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        5: ASM: class hugman.mubble.Mubble$ModRegistryEvents blocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        6: ASM: class hugman.mubble.Mubble$ModRegistryEvents tileEntitiesRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        7: ASM: class hugman.mubble.Mubble$ModRegistryEvents containersRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        8: ASM: class hugman.mubble.Mubble$ModRegistryEvents itemsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        9: ASM: class hugman.mubble.Mubble$ModRegistryEvents enchantmentsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        10: ASM: class hugman.mubble.Mubble$ModRegistryEvents paintingTypesRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
        11: ASM: class hugman.mubble.Mubble$ModRegistryEvents modDimensionsRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
    at hugman.mubble.init.MubbleItems.<clinit>(MubbleItems.java:98)
    at hugman.mubble.Mubble$ModRegistryEvents.itemsRegistry(Mubble.java:139)
    at net.minecraftforge.eventbus.ASMEventHandler_164_ModRegistryEvents_itemsRegistry_Register.invoke(.dynamic)
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
    at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
    at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
    at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
    at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
    at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
    at java.util.ArrayList.forEach(ArrayList.java:1257)
    at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
    at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
    at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
    at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
    at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964)
    at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
    at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
    at java.lang.ClassLoader.findClass(ClassLoader.java:530)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 22 more
>....       [09:23:16 [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for mo
did mubble]
java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
    at hugman.mubble.init.MubbleItems.<clinit>(MubbleItems.java:98) ~[?:?] {re:classloading}
    at hugman.mubble.Mubble$ModRegistryEvents.itemsRegistry(Mubble.java:139) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraftforge.eventbus.ASMEventHandler_164_ModRegistryEvents_itemsRegistry_Register.invoke(.dynamic) ~[?:?] {}
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
    at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.1] {re:classloading}
    at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_222] {}
    at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_222] {}
    at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) ~[?:?] {re:classloading}
    at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_222] {}
    at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964) [?:?] {re:classloading}
    at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) [?:?] {re:classloading}
    at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
    at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_222] {}
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222] {}
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222] {}
    ... 22 more
>....       [09:23:16 [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found]
>....       [09:23:16 [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception]
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
    Mubble (mubble) encountered an error during the load_registries event phase
§7net/minecraft/client/audio/ISound
]
    at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?] {re:classloading}
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?] {re:classloading}
    at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
>....       [09:23:16 [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: 
>....       [09:23:16 [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server]
>....       [09:23:16 [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds]
>....       [09:23:16 [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server]
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
    at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?] {re:classloading}
    at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1002) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:534) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:566) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:549) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {} 
```

It seems that ISound is a client-only method that the Server cannot handle, according to this thread on minecraftforge.net
https://www.minecraftforge.net/forum/topic/23518-solved-isound-crash-server/

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
