### ISSUE TITLE
Server - Player disconnects on using items that play sounds

### ISSUE THREAD

**Issue by JayJTD** [Hugman76/Mubble#61]
Bug #59 was able to fix the issue relating to the Server crashes relating to ISound however there is currently a bug that disconnects a player for activating items that use sounds files such as the Super Star.

Server Logs:
```>....       [22:56:08 [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /120.158.220.215:59783]
net.minecraft.crash.ReportedException: Ticking player
    at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:424) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:
creative_inventory_action_fix}
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329) [?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503_a()Lnet/minecraft/util/ResourceLocation;
    at hugman.mubble.objects.item.SuperStarItem.func_77654_b(SuperStarItem.java:27) ~[?:?] {re:classloading}
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:201) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2655) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:954) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init_ho
ok,pl:runtimedistcleaner:A}
    at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:classloading,pl:accesstransformer:B}
    ... 8 more

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
